// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnwtHzav1Bc2wsgI2Vq2so9Lfqd_tjSH0',
    appId: '1:810106839857:web:c48f1c51ce16786179c610',
    messagingSenderId: '810106839857',
    projectId: 'sos-app-834f6',
    authDomain: 'sos-app-834f6.firebaseapp.com',
    storageBucket: 'sos-app-834f6.appspot.com',
    measurementId: 'G-46GDYBXMVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFMrzUbFt_5J_WEBoEI2_U6Hjns2u4Slw',
    appId: '1:810106839857:android:fb7539316df3fe4679c610',
    messagingSenderId: '810106839857',
    projectId: 'sos-app-834f6',
    storageBucket: 'sos-app-834f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6YIiyt87vfr_T8VCZ3rC9zcK1GdU0mIA',
    appId: '1:810106839857:ios:6e0e7f56fc3f970579c610',
    messagingSenderId: '810106839857',
    projectId: 'sos-app-834f6',
    storageBucket: 'sos-app-834f6.appspot.com',
    iosBundleId: 'com.example.emergancyCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6YIiyt87vfr_T8VCZ3rC9zcK1GdU0mIA',
    appId: '1:810106839857:ios:6e0e7f56fc3f970579c610',
    messagingSenderId: '810106839857',
    projectId: 'sos-app-834f6',
    storageBucket: 'sos-app-834f6.appspot.com',
    iosBundleId: 'com.example.emergancyCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnwtHzav1Bc2wsgI2Vq2so9Lfqd_tjSH0',
    appId: '1:810106839857:web:fa65666ddb8de0ad79c610',
    messagingSenderId: '810106839857',
    projectId: 'sos-app-834f6',
    authDomain: 'sos-app-834f6.firebaseapp.com',
    storageBucket: 'sos-app-834f6.appspot.com',
    measurementId: 'G-X1RVFXDBSZ',
  );
}
